package com.vedanti.query.serv;

import com.vedanti.query.entity.FAQ;
import com.vedanti.query.repo.FAQRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;

@Service
public class ChatService {

    @Autowired
    private FAQRepository faqRepository;

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    public String getAnswer(String userQuestion) throws Exception {
        // First check DB
        List<FAQ> faqs = faqRepository.findByQuestionContainingIgnoreCase(userQuestion);
        if (!faqs.isEmpty()) {
            return faqs.get(0).getAnswer(); // Return first match
        }

        // Else call Gemini
        String answer = callGeminiAPI(userQuestion);

        // ✅ Clean the answer before saving
        String cleanAnswer = stripMarkdown(answer);

        // ✅ Save new Q&A into DB
        FAQ newFaq = new FAQ();
        newFaq.setQuestion(userQuestion);
        newFaq.setAnswer(cleanAnswer);
        faqRepository.save(newFaq);

        return cleanAnswer;
    }

    private String callGeminiAPI(String prompt) throws Exception {
        String model = "gemini-flash-latest"; // from AI Studio
        String url = "https://generativelanguage.googleapis.com/v1beta/models/"
                     + model + ":generateContent";

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(url))
            .header("Content-Type", "application/json")
            .header("X-goog-api-key", geminiApiKey) // ✅ use header, not ?key=
            .POST(HttpRequest.BodyPublishers.ofString(
                "{\"contents\":[{\"parts\":[{\"text\":\"" + prompt + "\"}]}]}"))
            .build();

        HttpResponse<String> response = HttpClient.newHttpClient()
            .send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Gemini API error (" + response.statusCode() + "): " + response.body());
        }

        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(response.body());

        JsonNode candidates = root.path("candidates");
        if (candidates.isMissingNode() || candidates.isEmpty()) {
            return "No answer generated by Gemini.";
        }

        return candidates.get(0)
                         .path("content")
                         .path("parts")
                         .get(0)
                         .path("text")
                         .asText("No response text found.");
    }

    // ✅ Utility method to strip markdown formatting
    private String stripMarkdown(String text) {
        if (text == null) return "";
        return text.replaceAll("\\*+", "")        // remove bold/italics markers
                   .replaceAll("(?m)^#{1,6}\\s*", "") // remove headings
                   .replaceAll("(?m)^-\\s*", "• ")    // convert lists to bullets
                   .replaceAll("(?m)^\\d+\\.\\s*", "") // remove numbered lists
                   .trim();
    }
}
