spring.application.name=chatbot
spring.datasource.url=jdbc:mysql://localhost:3306/faqchatbot
spring.datasource.username=root
spring.datasource.password=
gemini.api.key=AIzaSyCBg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
