spring.application.name=uploadpapers
spring.datasource.url=jdbc:mysql://localhost:3306/faqchatbot
spring.datasource.username=root
spring.datasource.password=Vepo@Mysql0201
gemini.api.key=AIzaSyCBgCt1TkSPgJxJFxU9BherXYL-yGjv-zw
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
